### ISSUE TITLE
[Feature Request] Maintain letter case

### ISSUE THREAD

**Issue by IdoBar** [northword/zotero-format-metadata#17]
Thank you for developing this add-on, I've been waiting for ages for a tool that can help to format metadata easily and quickly!

I have a suggestion for another formatting option:
In many citation styles, the title is formatted in Title Case, which is not suitable for species names (which also need to be _italicized_).
I found that this can be done by adding the following HTML tags: `<i><span class="nocase">Genus species</span></i>`.
Is it possible to add this as a formatting option (or define my custom shortcut to achieve this)?

Thanks again, Ido

**Comment by northword** [comment]
Thank you for your suggestions! 

Version 0.3.2 adds this tag for temporary use, there are still some details not dealt with, such as icon and repeated application when nested HTML tags may remove other HTML tags nested in it, etc., which will be fixed in the next patch.

- shortcut: `ctrl` + `n` (If you have a better idea of what this shortcut setting is, please let me know.)
- toolbar have a button named `No Case`

Regarding the feature of defining custom shortcuts to add HTML tags, please allow me to think of a more efficient way to implement it, which will be implemented in a subsequent release.
