### ISSUE TITLE
[Bug] 选择 [更新所有字段并lint]后图书章节变图书

### ISSUE THREAD

**Issue by holderhe** [northword/zotero-format-metadata#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.5
- Addon Version: 1.19.3

### Describe the bug

选择 [更新所有字段并lint]后图书章节变图书，与#216相似。
复现文章doi：10.1007/978-3-030-36708-4_23

因为本人领域内经常会有这样的变化：arxiv（有doi，文章title随着提交版本可能变化）→会议（可能无doi，文章title可能变化）→会议集（无doi，有ISBN），的确是一个非常麻烦的事，而且这个变化时间上又有长有短，如果一不注意可能信息就变了，一些不是重点关注的文献就可能变了信息也不知道。
所以我会不定期更新所有字段，发现了这个小问题，希望作者修复一下。
此外，不知道作者是否可以增加一个判断方便选择是否更新item的类型，让用户决定最终的结果，以避免批量更新后i，tem类型变化，找不到原始的参考文献。

**Comment by northword** [comment]
根据你的描述，在 #216 中的这种类型的变化应是正常的、正确的？

而此 issue 中遇到的并不能够通过你所说的   不更新条目类型    就可以修复：

需要明确一件事情：不同的条目类型包含的字段是不同的。也就是说，本地为 “图书章节” 的条目，在执行此操作后，从数据库取得的数据为“图书”时，一方面，新旧字段类型不一致会导致数据丢失（如 book title, pages），另一方面，对于同一字段，如标题，API 返回的实际上已经是图书的标题而不是论文的标题了，因此即便条目类型没有改变，你也找不到。

**Comment by northword** [comment]
这边可以做这样的优化：当 DOI 存在于 extra 时，优先使用 DOI 而不是 ISBN 更新元数据。

**Comment by northword** [comment]
Added an option to request confirmation, default is closes.

Note: This confirmation window will block the main thread, i.e., you must complete the confirmation in order to perform subsequent actions (this plugin and the all Zotero activity).

![Clip_2024-10-17_21-36-20](https://github.com/user-attachments/assets/26fa805f-3700-4ab9-bef6-334d9f245e43)



![Clip_2024-10-17_21-30-34](https://github.com/user-attachments/assets/6ad5887f-0ddb-4de6-a510-89628071bf37)
